/******************************************************************************/
/*                         DNS Manutenções - 2018                             */
/******************************************************************************/

package dns.manutenções.view;

import dns.manutenções.control.Controlador;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author danie_000
 */
public class ClientesPanel extends javax.swing.JPanel
{

    @SuppressWarnings("FieldMayBeFinal")
    private Controlador control;
    
    DefaultListModel listModel = new DefaultListModel();
   
    public void atualizarLista()
    {
        listModel.clear();
        
        for(int i = 0; i < control.ctrlClientes().getPessoasClientes().size(); i++) 
        {
            listModel.addElement(control.ctrlClientes().getPessoasClientes().get(i));
        }
    }
    
    /**
     * Creates new form ClientesPanel
     * @param c
     */
    public ClientesPanel(Controlador c)
    {
        initComponents();
        this.control = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoAlterar = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        TextoEmail = new javax.swing.JTextField();
        TextoTelefone = new javax.swing.JTextField();
        TextoEndereco = new javax.swing.JTextField();
        TextoNome = new javax.swing.JTextField();
        TextoCpf = new javax.swing.JTextField();
        ScrollPanelClientesp = new javax.swing.JScrollPane();
        ListaPessoas = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(595, 322));
        setMinimumSize(new java.awt.Dimension(595, 322));
        setPreferredSize(new java.awt.Dimension(595, 322));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });
        add(BotaoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 120, 62));

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        add(BotaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, 60));

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });
        add(BotaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 60));

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        add(BotaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 120, 60));
        add(TextoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 330, 30));
        add(TextoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 330, 30));
        add(TextoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 330, 30));
        add(TextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 330, 30));

        TextoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCpfActionPerformed(evt);
            }
        });
        add(TextoCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, 30));

        ListaPessoas.setModel(listModel);
        ListaPessoas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaPessoasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaPessoasFocusLost(evt);
            }
        });
        ListaPessoas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaPessoasComponentShown(evt);
            }
        });
        ScrollPanelClientesp.setViewportView(ListaPessoas);

        add(ScrollPanelClientesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 430, 130));

        jButton1.setText("CPF");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        jButton2.setText("Nome");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, -1));

        jButton3.setText("Endereço");
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, -1));

        jButton4.setText("Telefone");
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, -1));

        jButton5.setText("E-mail");
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));

        BotaoExcluir.setText("Excluir");
        add(BotaoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 62));
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoAlterarActionPerformed
    {//GEN-HEADEREND:event_BotaoAlterarActionPerformed
        // TODO add your handling code here:
        if(control.ctrlClientes().validarCPF(TextoCpf.getText()))
        {
            TextoCpf.setEnabled(false);
            TextoNome.setEnabled(false);
            TextoNome.setText(control.ctrlClientes().getNomePessoas(TextoCpf.getText()));
            TextoEndereco.setText(control.ctrlClientes().getEnderecoPessoas(TextoCpf.getText()));
            TextoTelefone.setText(control.ctrlClientes().getTelefonePessoas(TextoCpf.getText()));
            TextoEmail.setText(control.ctrlClientes().getEmailPessoas(TextoCpf.getText()));
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Cliente com esse CPF");
        }
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoSalvarActionPerformed
    {//GEN-HEADEREND:event_BotaoSalvarActionPerformed
        // TODO add your handling code here:
        TextoCpf.setEnabled(true);
        TextoNome.setEnabled(true);
        if((!"".equals(TextoCpf.getText()))&&(!"".equals(TextoEmail.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoEndereco.getText()))&&(!"".equals(TextoTelefone.getText())))
        {
            control.ctrlClientes().AlterarPessoa(control.ctrlClientes().getPessoa(TextoCpf.getText()),TextoEmail.getText(),TextoEndereco.getText(),TextoTelefone.getText());
            JOptionPane.showMessageDialog(null,"Alterado com Sucesso!");
        }
        else
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar pois há campos vazios!");

        TextoCpf.setText("");
        TextoEmail.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoLimparActionPerformed
    {//GEN-HEADEREND:event_BotaoLimparActionPerformed
        TextoCpf.setText("");
        TextoEmail.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
        TextoCpf.setEnabled(true);
        TextoNome.setEnabled(true);
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoCadastrarActionPerformed
    {//GEN-HEADEREND:event_BotaoCadastrarActionPerformed
        if((!"".equals(TextoCpf.getText()))&&(!"".equals(TextoEmail.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoEndereco.getText()))&&(!"".equals(TextoTelefone.getText())))
        {
            if(control.ctrlClientes().CadastrarPessoa(TextoCpf.getText( ),TextoEmail.getText(),TextoNome.getText(),TextoEndereco.getText(),TextoTelefone.getText()))
            {
                atualizarLista();
                JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!");
            }

            else
            {
                System.out.println("Erro ao cadastrar");
                JOptionPane.showMessageDialog(null,"Ja existe Cliente com esse CPF");
            }
        }
        else
            JOptionPane.showMessageDialog(null,"Não foi possivel Cadastar, pois há campos vazios!");
        
        TextoCpf.setText("");
        TextoEmail.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void TextoCpfActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextoCpfActionPerformed
    {//GEN-HEADEREND:event_TextoCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCpfActionPerformed

    private void ListaPessoasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPessoasFocusGained
    {//GEN-HEADEREND:event_ListaPessoasFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaPessoasFocusGained

    private void ListaPessoasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPessoasFocusLost
    {//GEN-HEADEREND:event_ListaPessoasFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaPessoasFocusLost

    private void ListaPessoasComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaPessoasComponentShown
    {//GEN-HEADEREND:event_ListaPessoasComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaPessoasComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JList ListaPessoas;
    private javax.swing.JScrollPane ScrollPanelClientesp;
    private javax.swing.JTextField TextoCpf;
    private javax.swing.JTextField TextoEmail;
    private javax.swing.JTextField TextoEndereco;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JTextField TextoTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
