/******************************************************************************/
/*                         DNS Manutenções - 2018                             */
/******************************************************************************/

package dns.manutenções.view;

import dns.manutenções.control.Controlador;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author danie_000
 */
public class FuncionariosPanel extends javax.swing.JPanel
{
    @SuppressWarnings("FieldMayBeFinal")
    private Controlador control;
    DefaultListModel listModel = new DefaultListModel();
    
    /**
     * Creates new form FuncionariosPanel
     * @param c
     */
    public FuncionariosPanel(Controlador c)
    {
        this.control = c;
        
        initComponents();
    }

    public void atualizarLista()
    {
        listModel.clear();
        
        for(int i = 0; i < control.ctrlFuncionarios().getListaFuncionarios().size(); i++) 
        {
            listModel.addElement(control.ctrlFuncionarios().getListaFuncionarios().get(i));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanelClientesp4 = new javax.swing.JScrollPane();
        ListaFuncionarios = new javax.swing.JList();
        TextoMatricula = new javax.swing.JTextField();
        TextoNome = new javax.swing.JTextField();
        TextoEndereco = new javax.swing.JTextField();
        TextoTelefone = new javax.swing.JTextField();
        TextoSalario = new javax.swing.JTextField();
        BotaoAlterar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(595, 322));
        setMinimumSize(new java.awt.Dimension(595, 322));
        setPreferredSize(new java.awt.Dimension(595, 322));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListaFuncionarios.setModel(listModel);
        ListaFuncionarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaFuncionariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaFuncionariosFocusLost(evt);
            }
        });
        ListaFuncionarios.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaFuncionariosComponentShown(evt);
            }
        });
        ScrollPanelClientesp4.setViewportView(ListaFuncionarios);

        add(ScrollPanelClientesp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 430, 130));

        TextoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoMatriculaActionPerformed(evt);
            }
        });
        add(TextoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, 30));
        add(TextoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 330, 30));
        add(TextoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 330, 30));
        add(TextoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 330, 30));

        TextoSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoSalarioActionPerformed(evt);
            }
        });
        add(TextoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 330, 30));

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });
        add(BotaoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 120, 62));

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });
        add(BotaoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 62));

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.setMaximumSize(new java.awt.Dimension(122, 62));
        BotaoSalvar.setMinimumSize(new java.awt.Dimension(122, 62));
        BotaoSalvar.setPreferredSize(new java.awt.Dimension(122, 62));
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        add(BotaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, 60));

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });
        add(BotaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 60));

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoCadastrar.setMinimumSize(new java.awt.Dimension(63, 23));
        BotaoCadastrar.setPreferredSize(new java.awt.Dimension(63, 23));
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        add(BotaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 120, 60));

        jButton1.setText("Matrícula");
        jButton1.setBorderPainted(false);
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.setRolloverEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        jButton2.setText("Nome");
        jButton2.setBorderPainted(false);
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.setRolloverEnabled(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 90, 30));

        jButton3.setText("Endereço");
        jButton3.setBorderPainted(false);
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setRolloverEnabled(false);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 30));

        jButton4.setText("Telefone");
        jButton4.setBorderPainted(false);
        jButton4.setDefaultCapable(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setRequestFocusEnabled(false);
        jButton4.setRolloverEnabled(false);
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 30));

        jButton5.setText("Salário");
        jButton5.setBorderPainted(false);
        jButton5.setDefaultCapable(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setRequestFocusEnabled(false);
        jButton5.setRolloverEnabled(false);
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void ListaFuncionariosFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaFuncionariosFocusGained
    {//GEN-HEADEREND:event_ListaFuncionariosFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaFuncionariosFocusGained

    private void ListaFuncionariosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaFuncionariosFocusLost
    {//GEN-HEADEREND:event_ListaFuncionariosFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaFuncionariosFocusLost

    private void ListaFuncionariosComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaFuncionariosComponentShown
    {//GEN-HEADEREND:event_ListaFuncionariosComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaFuncionariosComponentShown

    private void TextoMatriculaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextoMatriculaActionPerformed
    {//GEN-HEADEREND:event_TextoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoMatriculaActionPerformed

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoAlterarActionPerformed
    {//GEN-HEADEREND:event_BotaoAlterarActionPerformed
        // TODO add your handling code here:
        if(!control.ctrlFuncionarios().validaMatricula(TextoMatricula.getText()))
        {
            TextoMatricula.setEnabled(false);
            TextoNome.setEnabled(false);
            TextoNome.setText(control.ctrlFuncionarios().getNomeFuncionario(TextoMatricula.getText()));
            TextoEndereco.setText(control.ctrlFuncionarios().getEndFuncionario(TextoMatricula.getText()));
            TextoTelefone.setText(control.ctrlFuncionarios().getTelFuncionario(TextoMatricula.getText()));
            TextoSalario.setText(String.valueOf(control.ctrlFuncionarios().getSalarioFuncionario(TextoMatricula.getText())));
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Funcionario com essa Matricula");
        }
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoExcluirActionPerformed
    {//GEN-HEADEREND:event_BotaoExcluirActionPerformed
        if(!control.ctrlFuncionarios().validaMatricula(TextoMatricula.getText()))
        {
            control.ctrlFuncionarios().ExcluirFuncionario(control.ctrlFuncionarios().getFuncionario(TextoMatricula.getText()));
            listModel.removeElement(control.ctrlFuncionarios().getNomeFuncionario((TextoMatricula.getText())));

            this.atualizarLista();
            JOptionPane.showMessageDialog(null,"Excluido com Sucesso!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Funcionario com essa mattricula");
        }

        TextoMatricula.setText("");
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoSalvarActionPerformed
    {//GEN-HEADEREND:event_BotaoSalvarActionPerformed
        // TODO add your handling code here:
        TextoMatricula.setEnabled(true);
        TextoNome.setEnabled(true);
        try{
            if((!"".equals(TextoMatricula.getText()))&&(!"".equals(TextoSalario.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoEndereco.getText()))&&(!"".equals(TextoTelefone.getText())))
            {
                control.ctrlFuncionarios().AlterarFuncionario(control.ctrlFuncionarios().getFuncionario(TextoMatricula.getText()),Float.parseFloat(TextoSalario.getText()),TextoEndereco.getText(),TextoTelefone.getText());
                JOptionPane.showMessageDialog(null,"Alterado com Sucesso!");
            }
            else
                JOptionPane.showMessageDialog(null,"Não foi possivel alterar pois há campos vazios!");
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar, Salário inválido!");
        }
        TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoLimparActionPerformed
    {//GEN-HEADEREND:event_BotaoLimparActionPerformed
        TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
        TextoMatricula.setEnabled(true);
        TextoNome.setEnabled(true);
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoCadastrarActionPerformed
    {//GEN-HEADEREND:event_BotaoCadastrarActionPerformed
        try
        {
            if((!"".equals(TextoMatricula.getText()))&&(!"".equals(TextoSalario.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoEndereco.getText()))&&(!"".equals(TextoTelefone.getText())))
            {
                if(control.ctrlFuncionarios().CadastrarFuncionario(TextoMatricula.getText( ),Float.parseFloat(TextoSalario.getText()),TextoNome.getText(),TextoEndereco.getText(),TextoTelefone.getText()))
                {
                    atualizarLista();
                    JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!");
                }

                else
                {
                    System.out.println("Erro ao cadastrar");
                    JOptionPane.showMessageDialog(null,"Ja existe Funcionario com essa matricula");
                }
            }
            else
                JOptionPane.showMessageDialog(null,"Não foi possivel Cadastar, pois há campos vazios!");
        }
        catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null,"Salário inválido!");
        }
        
        TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");
    
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextoSalarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextoSalarioActionPerformed
    {//GEN-HEADEREND:event_TextoSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoSalarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JList ListaFuncionarios;
    private javax.swing.JScrollPane ScrollPanelClientesp4;
    private javax.swing.JTextField TextoEndereco;
    private javax.swing.JTextField TextoMatricula;
    private javax.swing.JTextField TextoNome;
    private javax.swing.JTextField TextoSalario;
    private javax.swing.JTextField TextoTelefone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
