/******************************************************************************/
/*                         DNS Manutenções - 2018                             */
/******************************************************************************/

package dns.manutenções.view;

import dns.manutenções.control.Controlador;

/**
 *
 * @author danie_000
 */
public class JanelaDNS extends javax.swing.JFrame
{
    @SuppressWarnings("FieldMayBeFinal")
    private Controlador control = new Controlador();
    
    private FuncionariosPanel funcionariosPanel = new FuncionariosPanel(control);
    private EmpresasPanel empresasPanel = new EmpresasPanel(control);
    private ServicosPanel servicosPanel = new ServicosPanel(control);
    private ClientesPanel pessoasPanel = new ClientesPanel(control);
    private PecasPanel pecasPanel = new PecasPanel(control);

    /**
     * Creates new form JanelaDNS
     */
    public JanelaDNS()
    {
        initComponents();
        
        principalPanel.addTab("Serviços", servicosPanel);
        principalPanel.addTab("Funcionarios", funcionariosPanel);
        principalPanel.addTab("Empresas", empresasPanel);
        principalPanel.addTab("Pessoas", pessoasPanel);
        principalPanel.addTab("Peças", pecasPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(590, 410));
        setMinimumSize(new java.awt.Dimension(590, 410));
        setName("Main"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 420));
        setResizable(false);
        setSize(new java.awt.Dimension(590, 410));
        getContentPane().setLayout(new java.awt.CardLayout());

        principalPanel.setMaximumSize(new java.awt.Dimension(600, 420));
        principalPanel.setMinimumSize(new java.awt.Dimension(600, 420));
        principalPanel.setPreferredSize(new java.awt.Dimension(600, 380));
        getContentPane().add(principalPanel, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JanelaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JanelaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JanelaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JanelaDNS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                JanelaDNS janela = new JanelaDNS();
                
                janela.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane principalPanel;
    // End of variables declaration//GEN-END:variables
}
