/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dns.manutenções.view;

import dns.manutenções.control.Controlador;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author danie_000
 */
public class PecasPanel extends javax.swing.JPanel
{
    @SuppressWarnings("FieldMayBeFinal")
    private Controlador control;
    
    DefaultListModel listModel = new DefaultListModel();
   
    public void atualizarLista()
    {
        listModel.clear();
        
        for(int i = 0; i < control.ctrlPecas().getListaPecas().size(); i++) 
        {
            listModel.addElement(control.ctrlPecas().getListaPecas().get(i));
        }
        
    }
     
    /**
     * Creates new form PecasPanel
     * @param c
     */
    public PecasPanel(Controlador c)
    {        
        this.control = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoAlterar = new javax.swing.JButton();
        BotaoExcluir = new javax.swing.JButton();
        BotaoSalvar = new javax.swing.JButton();
        BotaoLimpar = new javax.swing.JButton();
        BotaoCadastrar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TextoValor = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TextoPreço = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextoNome = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextoCodigo = new javax.swing.JTextPane();
        ScrollPanelClientesp = new javax.swing.JScrollPane();
        ListaPeças = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(595, 322));
        setMinimumSize(new java.awt.Dimension(595, 322));
        setPreferredSize(new java.awt.Dimension(595, 322));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });
        add(BotaoAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 120, 62));

        BotaoExcluir.setText("Excluir");
        BotaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoExcluirActionPerformed(evt);
            }
        });
        add(BotaoExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 120, 62));

        BotaoSalvar.setText("Salvar");
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        add(BotaoSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, 60));

        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });
        add(BotaoLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 60));

        BotaoCadastrar.setText("Cadastrar");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });
        add(BotaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 120, 60));

        jScrollPane4.setViewportView(TextoValor);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 330, -1));

        jScrollPane3.setViewportView(TextoPreço);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 330, -1));

        jScrollPane2.setViewportView(TextoNome);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 330, -1));

        jScrollPane1.setViewportView(TextoCodigo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, -1));

        ListaPeças.setModel(listModel);
        ListaPeças.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaPeçasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaPeçasFocusLost(evt);
            }
        });
        ListaPeças.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaPeçasComponentShown(evt);
            }
        });
        ScrollPanelClientesp.setViewportView(ListaPeças);

        add(ScrollPanelClientesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 430, 130));

        jButton1.setText("Código");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRolloverEnabled(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, -1));

        jButton2.setText("Nome");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setRolloverEnabled(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 90, -1));

        jButton3.setText("Preço");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRolloverEnabled(false);
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 90, -1));

        jButton4.setText("Valor");
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setRolloverEnabled(false);
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 90, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 430, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoAlterarActionPerformed
    {//GEN-HEADEREND:event_BotaoAlterarActionPerformed

        if(control.ctrlPecas().validarCODIGO(TextoCodigo.getText()))
        {
            TextoCodigo.setEnabled(false);
            TextoNome.setEnabled(false);
            TextoNome.setText(control.ctrlPecas().getNomePecas(TextoCodigo.getText()));
            TextoPreço.setText(String.valueOf(control.ctrlPecas().getPrecoPecas(TextoCodigo.getText())));                TextoValor.setText(String.valueOf(control.ctrlPecas().getValorPecas(TextoCodigo.getText())));
        }

        else 
        {
            JOptionPane.showMessageDialog(null,"Não existe Peças com esse CODIGO");
        }
        
    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void BotaoExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoExcluirActionPerformed
    {//GEN-HEADEREND:event_BotaoExcluirActionPerformed
        // TODO add your handling code here:
        if(control.ctrlPecas().validarCODIGO(TextoCodigo.getText()))
        {
            control.ctrlPecas().ExcluirPeca(control.ctrlPecas().getPeca(TextoCodigo.getText()));
            listModel.removeElement(control.ctrlPecas().getNomePecas((TextoCodigo.getText())));
            
            atualizarLista();
            JOptionPane.showMessageDialog(null,"Excluido com Sucesso!");
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não existe Peças com esse CODIGO");
        }
        
        TextoCodigo.setText("");
    }//GEN-LAST:event_BotaoExcluirActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoSalvarActionPerformed
    {//GEN-HEADEREND:event_BotaoSalvarActionPerformed
        TextoCodigo.setEnabled(true);
        TextoNome.setEnabled(true);
        try{
            if((!"".equals(TextoNome.getText()))&&(!"".equals(TextoCodigo.getText()))&&(!"".equals(TextoPreço.getText()))&&(!"".equals(TextoValor.getText())))
            {
                control.ctrlPecas().AlterarPeca(control.ctrlPecas().getPeca(TextoCodigo.getText()),Float.parseFloat(TextoValor.getText()));
                JOptionPane.showMessageDialog(null,"Alterado com Sucesso!");
            }
            else
                JOptionPane.showMessageDialog(null,"Não foi possivel alterar pois há campos vazios!");
        }catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar, valor inválido ou preço invalido!");
        }
        TextoCodigo.setText("");
        TextoNome.setText("");
        TextoPreço.setText("");
        TextoValor.setText("");
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoLimparActionPerformed
    {//GEN-HEADEREND:event_BotaoLimparActionPerformed
        TextoCodigo.setText("");
        TextoNome.setText("");
        TextoPreço.setText("");
        TextoValor.setText("");
    }//GEN-LAST:event_BotaoLimparActionPerformed

    /**  Remova os comentários do botão abaixo para 
      *  habilitar a função de subtrair do saldo o 
      *  preço da peça.
      */
    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaoCadastrarActionPerformed
    {//GEN-HEADEREND:event_BotaoCadastrarActionPerformed
        try{
            if((!"".equals(TextoCodigo.getText()))&&(!"".equals(TextoNome.getText()))&&(!"".equals(TextoPreço.getText()))&&(!"".equals(TextoValor.getText())))
            {
                //if((control.getWe().getSaldo()) < (Float.parseFloat(TextoPreço.getText())))
                //{
                    if(control.ctrlPecas().CadastrarPeca(TextoCodigo.getText(),TextoNome.getText(),Float.parseFloat(TextoPreço.getText()),Float.parseFloat(TextoValor.getText())))
                    {
                        //control.getWe().subSaldo(Float.parseFloat(TextoPreço.getText()));
                        atualizarLista();
                        JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso!");
                    }
                    else
                    {
                    System.out.println("Erro ao cadastrar");
                    JOptionPane.showMessageDialog(null,"Ja existe Peça com esse CODIGO");
                    }
                //}
                //else
                //{
                //    JOptionPane.showMessageDialog(null,"Erro ao adquirir peça: Saldo insuficiente");
                //}
            }
            else
                JOptionPane.showMessageDialog(null,"Não foi possivel Cadastar, pois há campos vazios!");
        }catch(NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar, valor inválido ou preço invalido!");
        }
        TextoCodigo.setText("");
        TextoNome.setText("");
        TextoPreço.setText("");
        TextoValor.setText("");
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void ListaPeçasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPeçasFocusGained
    {//GEN-HEADEREND:event_ListaPeçasFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaPeçasFocusGained

    private void ListaPeçasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPeçasFocusLost
    {//GEN-HEADEREND:event_ListaPeçasFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaPeçasFocusLost

    private void ListaPeçasComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaPeçasComponentShown
    {//GEN-HEADEREND:event_ListaPeçasComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaPeçasComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JButton BotaoExcluir;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JButton BotaoSalvar;
    private javax.swing.JList ListaPeças;
    private javax.swing.JScrollPane ScrollPanelClientesp;
    private javax.swing.JTextPane TextoCodigo;
    private javax.swing.JTextPane TextoNome;
    private javax.swing.JTextPane TextoPreço;
    private javax.swing.JTextPane TextoValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
