/******************************************************************************/
/*                         DNS Manutenções - 2018                             */
/******************************************************************************/

package dns.manutenções.view;

import dns.manutenções.control.Controlador;
import dns.manutenções.model.Cliente;
import dns.manutenções.model.Funcionario;
import dns.manutenções.model.Peca;
import dns.manutenções.model.Servico;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author danie_000
 */
public class ServicosPanel extends javax.swing.JPanel
{
    @SuppressWarnings("FieldMayBeFinal")
    private Controlador control;
    
    DefaultListModel funcionariosListModel = new DefaultListModel();
    DefaultListModel clientesListModel = new DefaultListModel();
    DefaultListModel pecasListModel = new DefaultListModel();
    DefaultListModel servicosListModel = new DefaultListModel();

    DefaultComboBoxModel clientesBox = new DefaultComboBoxModel();
    DefaultComboBoxModel funcionariosBox = new DefaultComboBoxModel();
    
    public void atualizarListaFuncionarios()
    {
        funcionariosListModel.clear();
        
        for(int i = 0; i < control.ctrlFuncionarios().getListaFuncionarios().size(); i++) 
        {
            funcionariosListModel.addElement(control.ctrlFuncionarios().getListaFuncionarios().get(i));
        }
    }
    
    public void atualizarListaClientes()
    {
        clientesListModel.clear();
        
        for(int i = 0; i < control.ctrlClientes().getPessoasClientes().size(); i++) 
        {
            clientesListModel.addElement(control.ctrlClientes().getPessoasClientes().get(i));
        }
        
        for(int i = 0; i < control.ctrlClientes().getEmpresasClientes().size(); i++) 
        {
            clientesListModel.addElement(control.ctrlClientes().getEmpresasClientes().get(i));
        }
    }
    
    public void atualizarListaPecas()
    {
        pecasListModel.clear();
        
        for(int i = 0; i < control.ctrlPecas().getListaPecas().size(); i++) 
        {
            pecasListModel.addElement(control.ctrlPecas().getListaPecas().get(i));
        }
        
    }
    
    public void atualizarListaServicos()
    {
        servicosListModel.clear();
        
        for(int i = 0; i < control.getServicos().size(); i++) 
        {
            servicosListModel.addElement(control.getServicos().get(i));
        }
    }
            
    /**
     * Creates new form ClientesPanel
     * @param c
     */
    public ServicosPanel(Controlador c)
    {   
        this.control = c;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovoServicoPanel = new javax.swing.JDialog();
        ClientesComboBox = new javax.swing.JComboBox<>();
        FuncionariosComboBox = new javax.swing.JComboBox<>();
        TextoData = new javax.swing.JFormattedTextField();
        TextoValor = new javax.swing.JTextField();
        ConfirmarAgendamentoButton = new javax.swing.JButton();
        CancelarAgendamentoButton = new javax.swing.JButton();
        ScrollPanelClientesp4 = new javax.swing.JScrollPane();
        ListaFuncionarios = new javax.swing.JList();
        ScrollPanelClientesp1 = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList();
        ScrollPanelClientesp2 = new javax.swing.JScrollPane();
        ListaPecas = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ConcluirAlt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        NovoGerarRelatorio = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        TotalArr = new javax.swing.JLabel();
        TotalnArre = new javax.swing.JLabel();
        TotalGasto = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Gerar = new javax.swing.JButton();
        TG = new javax.swing.JTextField();
        TA = new javax.swing.JTextField();
        TNA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SC = new javax.swing.JTextField();
        SP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        serviçosLabel = new javax.swing.JButton();
        ScrollPanelClientesp = new javax.swing.JScrollPane();
        ListaServiços = new javax.swing.JList();
        AgendarButton = new javax.swing.JButton();
        RealizarServicoButton = new javax.swing.JButton();
        RelatorioButton = new javax.swing.JButton();
        SaldoLabel = new javax.swing.JLabel();
        ServicosConcluidosLabel = new javax.swing.JLabel();
        CancelarServicoButton = new javax.swing.JButton();
        AlterarServicoButton = new javax.swing.JButton();
        FuncionariosLabel = new javax.swing.JLabel();
        ServicosPendentesLabel = new javax.swing.JLabel();
        DescontoButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        NovoServicoPanel.setTitle("Agendar Serviço - DNS Manutenções");
        NovoServicoPanel.setLocation(new java.awt.Point(500, 400));
        NovoServicoPanel.setLocationByPlatform(true);
        NovoServicoPanel.setMaximumSize(new java.awt.Dimension(610, 315));
        NovoServicoPanel.setMinimumSize(new java.awt.Dimension(610, 315));
        NovoServicoPanel.setPreferredSize(new java.awt.Dimension(610, 315));
        NovoServicoPanel.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientesComboBox.setModel(clientesBox);
        NovoServicoPanel.getContentPane().add(ClientesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 100, 30));

        FuncionariosComboBox.setModel(funcionariosBox);
        NovoServicoPanel.getContentPane().add(FuncionariosComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 100, 30));

        TextoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        TextoData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDataActionPerformed(evt);
            }
        });
        NovoServicoPanel.getContentPane().add(TextoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, -1));
        NovoServicoPanel.getContentPane().add(TextoValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 110, -1));

        ConfirmarAgendamentoButton.setText("Agendar");
        ConfirmarAgendamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarAgendamentoButtonActionPerformed(evt);
            }
        });
        NovoServicoPanel.getContentPane().add(ConfirmarAgendamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 110, 40));

        CancelarAgendamentoButton.setText("Cancelar");
        CancelarAgendamentoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarAgendamentoButtonActionPerformed(evt);
            }
        });
        NovoServicoPanel.getContentPane().add(CancelarAgendamentoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 110, 40));

        ListaFuncionarios.setModel(funcionariosListModel);
        ListaFuncionarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaFuncionarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaFuncionariosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaFuncionariosFocusLost(evt);
            }
        });
        ListaFuncionarios.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaFuncionariosComponentShown(evt);
            }
        });
        ListaFuncionarios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaFuncionariosValueChanged(evt);
            }
        });
        ScrollPanelClientesp4.setViewportView(ListaFuncionarios);

        NovoServicoPanel.getContentPane().add(ScrollPanelClientesp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 220));

        ListaClientes.setModel(clientesListModel);
        ListaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaClientesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaClientesFocusLost(evt);
            }
        });
        ListaClientes.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaClientesComponentShown(evt);
            }
        });
        ListaClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaClientesValueChanged(evt);
            }
        });
        ScrollPanelClientesp1.setViewportView(ListaClientes);

        NovoServicoPanel.getContentPane().add(ScrollPanelClientesp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 130, 220));

        ListaPecas.setModel(pecasListModel);
        ListaPecas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaPecasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaPecasFocusLost(evt);
            }
        });
        ListaPecas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaPecasComponentShown(evt);
            }
        });
        ListaPecas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaPecasValueChanged(evt);
            }
        });
        ScrollPanelClientesp2.setViewportView(ListaPecas);

        NovoServicoPanel.getContentPane().add(ScrollPanelClientesp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 130, 220));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Funcionários");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clientes");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 20));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Peças");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 130, 20));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Valor");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NovoServicoPanel.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 110, 20));

        ConcluirAlt.setText(" Alterar");
        ConcluirAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConcluirAltActionPerformed(evt);
            }
        });
        NovoServicoPanel.getContentPane().add(ConcluirAlt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 110, 40));

        jButton1.setText("jButton1");

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(100, 100));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jDesktopPane1.setRequestFocusEnabled(false);

        TotalArr.setText("Total Arrecadado");
        jDesktopPane1.add(TotalArr);
        TotalArr.setBounds(20, 50, 100, 50);

        TotalnArre.setText("Total ainda a arrecadar");
        jDesktopPane1.add(TotalnArre);
        TotalnArre.setBounds(130, 50, 130, 50);

        TotalGasto.setText("Total Gasto");
        jDesktopPane1.add(TotalGasto);
        TotalGasto.setBounds(270, 50, 80, 50);

        jButton2.setText("RELATORIO");
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(10, 10, 370, 23);

        Gerar.setText("Gerar");
        Gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(Gerar);
        Gerar.setBounds(150, 240, 73, 23);
        jDesktopPane1.add(TG);
        TG.setBounds(260, 120, 90, 30);
        jDesktopPane1.add(TA);
        TA.setBounds(20, 120, 90, 30);
        jDesktopPane1.add(TNA);
        TNA.setBounds(140, 120, 90, 30);

        jLabel1.setText("Serviços Concluidos");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(20, 180, 130, 20);

        jLabel2.setText("Serviços Pendentes");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(240, 180, 130, 20);
        jDesktopPane1.add(SC);
        SC.setBounds(20, 200, 100, 30);
        jDesktopPane1.add(SP);
        SP.setBounds(240, 200, 100, 30);

        NovoGerarRelatorio.getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jTextPane1);

        setMaximumSize(new java.awt.Dimension(595, 322));
        setMinimumSize(new java.awt.Dimension(595, 322));
        setPreferredSize(new java.awt.Dimension(595, 322));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(null);

        serviçosLabel.setText("Serviços");
        serviçosLabel.setDefaultCapable(false);
        serviçosLabel.setFocusPainted(false);
        serviçosLabel.setFocusable(false);
        serviçosLabel.setRequestFocusEnabled(false);
        serviçosLabel.setRolloverEnabled(false);
        add(serviçosLabel);
        serviçosLabel.setBounds(10, 10, 280, 22);

        ListaServiços.setModel(servicosListModel);
        ListaServiços.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ListaServiçosComponentAdded(evt);
            }
        });
        ListaServiços.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ListaServiçosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ListaServiçosFocusLost(evt);
            }
        });
        ListaServiços.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ListaServiçosComponentShown(evt);
            }
        });
        ListaServiços.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaServiçosValueChanged(evt);
            }
        });
        ScrollPanelClientesp.setViewportView(ListaServiços);

        add(ScrollPanelClientesp);
        ScrollPanelClientesp.setBounds(10, 40, 280, 290);

        AgendarButton.setText("Agendar");
        AgendarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarButtonActionPerformed(evt);
            }
        });
        add(AgendarButton);
        AgendarButton.setBounds(310, 160, 130, 50);

        RealizarServicoButton.setText("Concluir Serviço");
        RealizarServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarServicoButtonActionPerformed(evt);
            }
        });
        add(RealizarServicoButton);
        RealizarServicoButton.setBounds(310, 220, 130, 50);

        RelatorioButton.setText("Gerar Relatório");
        RelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioButtonActionPerformed(evt);
            }
        });
        add(RelatorioButton);
        RelatorioButton.setBounds(310, 280, 130, 50);

        SaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaldoLabel.setText("R$ " + this.control.getWe().getSaldo());
        SaldoLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Saldo"));
        add(SaldoLabel);
        SaldoLabel.setBounds(450, 70, 130, 50);

        ServicosConcluidosLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ServicosConcluidosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ServicosConcluidosLabel.setText(String.valueOf(control.getNumServicosConcluidos()));
        ServicosConcluidosLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Concluídos"));
        add(ServicosConcluidosLabel);
        ServicosConcluidosLabel.setBounds(310, 70, 130, 50);

        CancelarServicoButton.setText("Cancelar Serviço");
        CancelarServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarServicoButtonActionPerformed(evt);
            }
        });
        add(CancelarServicoButton);
        CancelarServicoButton.setBounds(450, 220, 130, 50);

        AlterarServicoButton.setText("Alterar Serviço");
        AlterarServicoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarServicoButtonActionPerformed(evt);
            }
        });
        add(AlterarServicoButton);
        AlterarServicoButton.setBounds(450, 160, 130, 50);

        FuncionariosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FuncionariosLabel.setText(String.valueOf(control.ctrlFuncionarios().getListaFuncionarios().size()));
        FuncionariosLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcionários"));
        add(FuncionariosLabel);
        FuncionariosLabel.setBounds(450, 10, 130, 50);

        ServicosPendentesLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ServicosPendentesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ServicosPendentesLabel.setText(String.valueOf(control.getNumServicosPendentes()));
        ServicosPendentesLabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pendentes"));
        add(ServicosPendentesLabel);
        ServicosPendentesLabel.setBounds(310, 10, 130, 50);

        DescontoButton.setText("Desconto");
        add(DescontoButton);
        DescontoButton.setBounds(450, 280, 130, 50);
        add(jSeparator1);
        jSeparator1.setBounds(310, 140, 270, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void ListaServiçosFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaServiçosFocusGained
    {//GEN-HEADEREND:event_ListaServiçosFocusGained
        
    }//GEN-LAST:event_ListaServiçosFocusGained

    private void ListaServiçosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaServiçosFocusLost
    {//GEN-HEADEREND:event_ListaServiçosFocusLost
        
    }//GEN-LAST:event_ListaServiçosFocusLost

    private void ListaServiçosComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaServiçosComponentShown
    {//GEN-HEADEREND:event_ListaServiçosComponentShown

    }//GEN-LAST:event_ListaServiçosComponentShown

    private void AgendarButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AgendarButtonActionPerformed
    {//GEN-HEADEREND:event_AgendarButtonActionPerformed
        ListaClientes.setVisible(true);
        this.atualizarListaClientes();
        this.atualizarListaFuncionarios();
        this.atualizarListaPecas();
        ConfirmarAgendamentoButton.setVisible(true);
        ConcluirAlt.setVisible(false);
        NovoServicoPanel.setVisible(true);
    }//GEN-LAST:event_AgendarButtonActionPerformed

    private void TextoDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TextoDataActionPerformed
    {//GEN-HEADEREND:event_TextoDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDataActionPerformed

    private void ListaFuncionariosFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaFuncionariosFocusGained
    {//GEN-HEADEREND:event_ListaFuncionariosFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaFuncionariosFocusGained

    private void ListaFuncionariosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaFuncionariosFocusLost
    {//GEN-HEADEREND:event_ListaFuncionariosFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaFuncionariosFocusLost

    private void ListaFuncionariosComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaFuncionariosComponentShown
    {//GEN-HEADEREND:event_ListaFuncionariosComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaFuncionariosComponentShown

    private void ListaClientesFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaClientesFocusGained
    {//GEN-HEADEREND:event_ListaClientesFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaClientesFocusGained

    private void ListaClientesFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaClientesFocusLost
    {//GEN-HEADEREND:event_ListaClientesFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaClientesFocusLost

    private void ListaClientesComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaClientesComponentShown
    {//GEN-HEADEREND:event_ListaClientesComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaClientesComponentShown

    private void ListaPecasFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPecasFocusGained
    {//GEN-HEADEREND:event_ListaPecasFocusGained
        /*if(control.getFuncionarios()!=null)
        {
            TextoMatricula.setText(control.getFuncionarios().get(0).getMatricula());
            //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
            TextoNome.setText(control.getFuncionarios().get(0).getNome());
            TextoEndereco.setText(control.getFuncionarios().get(0).getEndereco());
            TextoTelefone.setText(control.getFuncionarios().get(0).getTelefone());
        }*/
    }//GEN-LAST:event_ListaPecasFocusGained

    private void ListaPecasFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_ListaPecasFocusLost
    {//GEN-HEADEREND:event_ListaPecasFocusLost
        /*TextoMatricula.setText("");
        TextoSalario.setText("");
        TextoNome.setText("");
        TextoEndereco.setText("");
        TextoTelefone.setText("");*/
    }//GEN-LAST:event_ListaPecasFocusLost

    private void ListaPecasComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_ListaPecasComponentShown
    {//GEN-HEADEREND:event_ListaPecasComponentShown
        /*TextoMatricula.setText(control.getFuncionarios().get(1).getMatricula());
        //TextoSalario.setText(control.getFuncionarios().get(1).getSalario());
        TextoNome.setText(control.getFuncionarios().get(1).getNome());
        TextoEndereco.setText(control.getFuncionarios().get(1).getEndereco());
        TextoTelefone.setText(control.getFuncionarios().get(1).getTelefone());*/
    }//GEN-LAST:event_ListaPecasComponentShown

    private void ConfirmarAgendamentoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ConfirmarAgendamentoButtonActionPerformed
    {//GEN-HEADEREND:event_ConfirmarAgendamentoButtonActionPerformed
        try
        {
            control.cadastrarServico(Float.parseFloat(TextoValor.getText()), TextoData.getText(), (Cliente)ListaClientes.getSelectedValue(), (Funcionario)ListaFuncionarios.getSelectedValue(), (ArrayList<Peca>)ListaPecas.getSelectedValuesList());
        }
        catch(NumberFormatException exc)
        {
            JOptionPane.showMessageDialog(null,"Erro ao agendar serviço");
        }
        
        this.atualizarListaServicos();
        ServicosPendentesLabel.setText(String.valueOf(control.getNumServicosPendentes()));
        NovoServicoPanel.setVisible(false);
    }//GEN-LAST:event_ConfirmarAgendamentoButtonActionPerformed

    private void RealizarServicoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RealizarServicoButtonActionPerformed
    {//GEN-HEADEREND:event_RealizarServicoButtonActionPerformed
        try
        {
            if(!TextoData.getText().equals(""))
            {
                if(control.realizarServico((Servico)ListaServiços.getSelectedValue()))
                {
                    atualizarListaServicos();
                    SaldoLabel.setText("R$ " + this.control.getWe().getSaldo());
                    JOptionPane.showMessageDialog(null,"Serviço Concluído");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Serviço já realizado");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Forneça uma data no formato DD/MM/AAAA");
            }
        }
        catch(NullPointerException exc)
        {
            JOptionPane.showMessageDialog(null,"Selecione um serviço");
        }
        
        ServicosConcluidosLabel.setText(String.valueOf(control.getNumServicosConcluidos()));
        ServicosPendentesLabel.setText(String.valueOf(control.getNumServicosPendentes()));
    }//GEN-LAST:event_RealizarServicoButtonActionPerformed

    private void ListaFuncionariosValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_ListaFuncionariosValueChanged
    {//GEN-HEADEREND:event_ListaFuncionariosValueChanged
        try
        {
            TextoValor.setText(String.valueOf(control.setValorTotal((Funcionario)ListaFuncionarios.getSelectedValue(), (ArrayList<Peca>)ListaPecas.getSelectedValuesList())));
        }
        catch(ClassCastException | NullPointerException exc)
        {
            TextoValor.setText("");
        }
    }//GEN-LAST:event_ListaFuncionariosValueChanged

    private void ListaClientesValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_ListaClientesValueChanged
    {//GEN-HEADEREND:event_ListaClientesValueChanged
        try
        {
            TextoValor.setText(String.valueOf(control.setValorTotal((Funcionario)ListaFuncionarios.getSelectedValue(), (ArrayList<Peca>)ListaPecas.getSelectedValuesList())));
        }
        catch(ClassCastException | NullPointerException exc)
        {
            TextoValor.setText("");
        }
    }//GEN-LAST:event_ListaClientesValueChanged

    private void ListaPecasValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_ListaPecasValueChanged
    {//GEN-HEADEREND:event_ListaPecasValueChanged
        try
        {
            TextoValor.setText(String.valueOf(control.setValorTotal((Funcionario)ListaFuncionarios.getSelectedValue(), (ArrayList<Peca>)ListaPecas.getSelectedValuesList())));
        }
        catch(ClassCastException | NullPointerException exc)
        {
            TextoValor.setText("");
        }
    }//GEN-LAST:event_ListaPecasValueChanged

    private void CancelarAgendamentoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarAgendamentoButtonActionPerformed
    {//GEN-HEADEREND:event_CancelarAgendamentoButtonActionPerformed
        NovoServicoPanel.setVisible(false);
    }//GEN-LAST:event_CancelarAgendamentoButtonActionPerformed

    private void CancelarServicoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelarServicoButtonActionPerformed
    {//GEN-HEADEREND:event_CancelarServicoButtonActionPerformed
        try
        {
            if(control.cancelarServico((Servico)ListaServiços.getSelectedValue()))
            {
                ServicosPendentesLabel.setText(String.valueOf(control.getNumServicosPendentes()));
                JOptionPane.showMessageDialog(null,"Serviço cancelado");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Impossível cancelar serviço");
            }
        }
        catch(NullPointerException exc)
        {
            JOptionPane.showMessageDialog(null,"Selecione um serviço");
        }
    }//GEN-LAST:event_CancelarServicoButtonActionPerformed

    private void RelatorioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RelatorioButtonActionPerformed
    {//GEN-HEADEREND:event_RelatorioButtonActionPerformed
        NovoGerarRelatorio.setVisible(true); 
    }//GEN-LAST:event_RelatorioButtonActionPerformed

    //////////////////////////////////////////////////////
    /*          TERMINAR O BOTÃO ALTERAR SERVIÇO        */
    private void AlterarServicoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AlterarServicoButtonActionPerformed
    {//GEN-HEADEREND:event_AlterarServicoButtonActionPerformed
        try
        {
            if(control.busrcarEstado((Servico) ListaServiços.getSelectedValue())){
                NovoServicoPanel.setVisible(true);
                ConcluirAlt.setVisible(true);
                ConfirmarAgendamentoButton.setVisible(false); 
                ListaFuncionarios.setSelectedValue(control.buscarFuncionarioServico((Servico) ListaServiços.getSelectedValue()),true);
                ListaPecas.setSelectedValue(control.buscarPecaServico((Servico) ListaServiços.getSelectedValue()),true);
                ListaClientes.setSelectedValue(control.buscarClienteServico((Servico) ListaServiços.getSelectedValue()),true);  
                TextoData.setText(control.buscarData((Servico) ListaServiços.getSelectedValue()));
                TextoValor.setText(String.valueOf(control.buscarValor((Servico) ListaServiços.getSelectedValue())));
               
                ListaClientes.setVisible(false);
                
            }
            
            //liente c=(Cliente) ListaClientes.getSelectedValue());
            //ListaFuncionarios.setSelectedValue(String.valueOf(control.buscarFunServico((Cliente)ListaClientes.getSelectedValue())),true);  
            
        }
        catch(NullPointerException exc)
        {
            NovoServicoPanel.setVisible(false);
            JOptionPane.showMessageDialog(null,"Selecione um serviço");
        }
        
    }//GEN-LAST:event_AlterarServicoButtonActionPerformed

    private void ListaServiçosValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_ListaServiçosValueChanged
    {//GEN-HEADEREND:event_ListaServiçosValueChanged
        
    }//GEN-LAST:event_ListaServiçosValueChanged

    private void ListaServiçosComponentAdded(java.awt.event.ContainerEvent evt)//GEN-FIRST:event_ListaServiçosComponentAdded
    {//GEN-HEADEREND:event_ListaServiçosComponentAdded
        ServicosConcluidosLabel.setText(String.valueOf(control.getNumServicosConcluidos()));
        ServicosPendentesLabel.setText(String.valueOf(control.getNumServicosPendentes()));
    }//GEN-LAST:event_ListaServiçosComponentAdded

    private void formFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_formFocusGained
    {//GEN-HEADEREND:event_formFocusGained
        FuncionariosLabel.setText(String.valueOf(control.ctrlFuncionarios().getListaFuncionarios().size()));
    }//GEN-LAST:event_formFocusGained

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
        FuncionariosLabel.setText(String.valueOf(control.ctrlFuncionarios().getListaFuncionarios().size()));
        ServicosConcluidosLabel.setText(String.valueOf(control.getNumServicosConcluidos()));
        ServicosPendentesLabel.setText(String.valueOf(control.getNumServicosPendentes()));
        SaldoLabel.setText("R$ " + this.control.getWe().getSaldo());
    }//GEN-LAST:event_formComponentShown

    private void ConcluirAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConcluirAltActionPerformed
        // TODO add your handling code here:
       
        //ListaClientes.setVisible(true);
        try{
        if((!"".equals(Float.parseFloat(TextoValor.getText())))&&(!"".equals(TextoData.getText()))&&((Funcionario)ListaFuncionarios.getSelectedValue()!=null)&&((ArrayList<Peca>)ListaPecas.getSelectedValuesList()!=null))
        {
            control.alterarServico((Servico) ListaServiços.getSelectedValue(),Float.parseFloat(TextoValor.getText()), TextoData.getText(),(Funcionario)ListaFuncionarios.getSelectedValue(),(ArrayList<Peca>)ListaPecas.getSelectedValuesList());    
            JOptionPane.showMessageDialog(null,"Serviço alterado com sucesso!");
            NovoServicoPanel.setVisible(false);
               
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar!");
            NovoServicoPanel.setVisible(false);
        }
        this.atualizarListaClientes();
        this.atualizarListaFuncionarios();
        this.atualizarListaPecas();
        }
        catch(NumberFormatException exc)
        { 
            JOptionPane.showMessageDialog(null,"Não foi possivel alterar!");
            NovoServicoPanel.setVisible(false);
        }
        
        
        
        
    }//GEN-LAST:event_ConcluirAltActionPerformed

    private void GerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarActionPerformed
        // TODO add your handling code here:
        TA.setText(String.valueOf(control.TotalArrecadado()));
        TNA.setText(String.valueOf(control.TotalAindaNaoArrecadado()));
        TG.setText(String.valueOf(control.TotalGasto()));
        
        SC.setText(String.valueOf(control.getNumServicosConcluidos()));
        SP.setText(String.valueOf(control.getNumServicosPendentes()));
    }//GEN-LAST:event_GerarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgendarButton;
    private javax.swing.JButton AlterarServicoButton;
    private javax.swing.JButton CancelarAgendamentoButton;
    private javax.swing.JButton CancelarServicoButton;
    private javax.swing.JComboBox<String> ClientesComboBox;
    private javax.swing.JButton ConcluirAlt;
    private javax.swing.JButton ConfirmarAgendamentoButton;
    private javax.swing.JButton DescontoButton;
    private javax.swing.JComboBox<String> FuncionariosComboBox;
    private javax.swing.JLabel FuncionariosLabel;
    private javax.swing.JButton Gerar;
    private javax.swing.JList ListaClientes;
    private javax.swing.JList ListaFuncionarios;
    private javax.swing.JList ListaPecas;
    private javax.swing.JList ListaServiços;
    private javax.swing.JDialog NovoGerarRelatorio;
    private javax.swing.JDialog NovoServicoPanel;
    private javax.swing.JButton RealizarServicoButton;
    private javax.swing.JButton RelatorioButton;
    private javax.swing.JTextField SC;
    private javax.swing.JTextField SP;
    private javax.swing.JLabel SaldoLabel;
    private javax.swing.JScrollPane ScrollPanelClientesp;
    private javax.swing.JScrollPane ScrollPanelClientesp1;
    private javax.swing.JScrollPane ScrollPanelClientesp2;
    private javax.swing.JScrollPane ScrollPanelClientesp4;
    private javax.swing.JLabel ServicosConcluidosLabel;
    private javax.swing.JLabel ServicosPendentesLabel;
    private javax.swing.JTextField TA;
    private javax.swing.JTextField TG;
    private javax.swing.JTextField TNA;
    private javax.swing.JFormattedTextField TextoData;
    private javax.swing.JTextField TextoValor;
    private javax.swing.JLabel TotalArr;
    private javax.swing.JLabel TotalGasto;
    private javax.swing.JLabel TotalnArre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton serviçosLabel;
    // End of variables declaration//GEN-END:variables
}
